import type { ICelestialBody, ISolarSystemConfig } from '@/types/solar-system.types'
import { colorConfig } from '@/configs/color.config'
import * as THREE from 'three'

const wireframed = true

export const solarSystemConfig: ISolarSystemConfig = {
  camera: {
    fov: 75,
    near: 0.1,
    far: 1000,
    position: new THREE.Vector3(0, 0, 50),
  },
  background: {
    color: colorConfig.pureBlack,
  },
  lights: {
    sun: {
      color: colorConfig.pureWhite,
      intensity: 30.00,
      distance: 1000,
      decay: 2.00,
    },
    ambient: {
      color: colorConfig.ambientGrey,
      intensity: 1,
    },
  },
  stars: {
    color: colorConfig.pureWhite,
    count: 5000,
    size: 0.5,
    sizeAttenuation: true,
  },
  trails: {
    color: colorConfig.trailGrey,
    opacity: 0.5,
    linewidth: 1,
    segments: 128,
    transparent: true,
    side: THREE.DoubleSide,
  },
}

export const celestialBodiesConfig: Record<string, ICelestialBody> = {
  sun: {
    name: 'Sun',
    radius: 1,
    distance: 0,
    color: colorConfig.sunYellow,
    emissive: colorConfig.sunraysOrange,
    emissiveIntensity: 1,
    scale: 5,
    segments: 64,
    shininess: 0,
    selfRotationSpeed: 0.1,
    orbitalRotationSpeed: 0,
    wireframed,
  },
  mercury: {
    name: 'Mercury',
    radius: 1,
    distance: 15,
    color: colorConfig.mercuryBrown,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
  venus: {
    name: 'Venus',
    radius: 1,
    distance: 20,
    color: colorConfig.venusYellow,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
  earth: {
    name: 'Earth',
    radius: 1,
    distance: 15,
    color: colorConfig.earthBlue,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
  moon: {
    name: 'Moon',
    radius: 0.5,
    distance: 2,
    color: colorConfig.moonGrey,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 0.5,
    segments: 32,
    shininess: 40,
    selfRotationSpeed: 0.01,
    orbitalRotationSpeed: 0.1,
    wireframed,
  },
  mars: {
    name: 'Mars',
    radius: 1,
    distance: 20,
    color: colorConfig.marsRed,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
  jupiter: {
    name: 'Jupiter',
    radius: 1,
    distance: 30,
    color: colorConfig.jupiterOrange,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
  saturn: {
    name: 'Saturn',
    radius: 1,
    distance: 40,
    color: colorConfig.saturnYellow,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 2.5,
    segments: 32,
    shininess: 10,
    selfRotationSpeed: 0.001,
    orbitalRotationSpeed: 0.3,
    wireframed,
  },
  uranus: {
    name: 'Uranus',
    radius: 1,
    distance: 50,
    color: colorConfig.uranusCyan,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
  neptune: {
    name: 'Neptune',
    radius: 1,
    distance: 60,
    color: colorConfig.neptuneBlue,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
  pluto: {
    name: 'Pluto',
    radius: 1,
    distance: 70,
    color: colorConfig.plutoGrey,
    emissive: colorConfig.pureBlack,
    emissiveIntensity: 0,
    scale: 1,
    segments: 32,
    shininess: 15,
    selfRotationSpeed: 0.3,
    orbitalRotationSpeed: 0.5,
    wireframed,
  },
}
